### ISSUE TITLE
Broken on Discourse 2.1.0

### ISSUE THREAD

**Issue by Intelligent-Fanatics** [discourse-league/dl-teaser#4]
This plugin no longer works on Discourse 2.1.0, you can not tick the "Allow topic in this category to show up...." and another strangely labeled option underneath "en.lockdown.lockdown_enabled" can be checked and you can enter the user group, click "Save Category" but nothing saves or changes. Category and topics titles are still hidden to guests.

**Comment by joebuhlig** [comment]
I just completed a rename/rebrand of this plugin. I found a few bugs in the process that should help with this. Give it another try and let me know if the issues remain.

https://github.com/procourse/procourse-teaser/commit/700b53a5fd7fe011e4a943bb67e76f515c3ad6a2
